CONSTRAINTS = [
    "CREATE CONSTRAINT IF NOT EXISTS ON (u:User) ASSERT u.id IS UNIQUE",
    "CREATE CONSTRAINT IF NOT EXISTS ON (p:Project) ASSERT p.id IS UNIQUE",
    "CREATE CONSTRAINT IF NOT EXISTS ON (t:TrelloCard) ASSERT t.id IS UNIQUE",
    "CREATE CONSTRAINT IF NOT EXISTS ON (i:GitHubIssue) ASSERT i.id IS UNIQUE",
    "CREATE CONSTRAINT IF NOT EXISTS ON (pr:PullRequest) ASSERT pr.id IS UNIQUE",
    "CREATE CONSTRAINT IF NOT EXISTS ON (c:Commit) ASSERT c.sha IS UNIQUE",
    "CREATE CONSTRAINT IF NOT EXISTS ON (b:Branch) ASSERT b.name IS UNIQUE",
    "CREATE CONSTRAINT IF NOT EXISTS ON (m:Component) ASSERT m.name IS UNIQUE",
    "CREATE CONSTRAINT IF NOT EXISTS ON (d:Discussion) ASSERT d.id IS UNIQUE",
    "CREATE CONSTRAINT IF NOT EXISTS ON (r:Release) ASSERT r.name IS UNIQUE",
    "CREATE CONSTRAINT IF NOT EXISTS ON (doc:Document) ASSERT doc.id IS UNIQUE",
    "CREATE CONSTRAINT IF NOT EXISTS ON (task:LLMTask) ASSERT task.id IS UNIQUE",
]


def setup_constraints(connector):
    for query in CONSTRAINTS:
        connector.run(query)
