name: Deploy Backend

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Stop docker compose process
          uses: appleboy/ssh-action@v0.1.7
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              cd /root/project/BaYaga
              docker compose down -v

        - name: Copy files to server
          uses: appleboy/scp-action@v0.1.0
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_SSH_KEY }}
            source: "."
            target: "/root/project/BaYaga"

        - name: Build & restart
          uses: appleboy/ssh-action@v0.1.7
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              cd /root/project/BaYaga
              docker compose up --build -d
